name: Semantic Versioning
on:
  workflow_dispatch:

jobs:
  publish:
    # needs: [  ] Insert test workflows for C++ and python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog