name: Semantic Versioning
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/github
            @semantic-release/exec
            @semantic-release/changelog