name: Semantic Versioning
on:
  workflow_dispatch:

jobs:
  publish:
    # needs: [  ] Insert test workflows for C++ and python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -r requirements.txt

      - name: Build ROS2 workspace
        run: colcon build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog